name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  build-example:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install redux-yjs-bindings dependencies
        run: npm ci

      - name: Build redux-yjs-bindings package
        run: npm run build

      - name: Install examples/todo-mvc dependencies
        working-directory: ./examples/todo-mvc
        run: npm ci --legacy-peer-deps

      - name: Build examples/todo-mvc
        working-directory: ./examples/todo-mvc
        run: npm run build:ci

      - name: Upload build files
        uses: actions/upload-artifact@v2
        if: github.repository == 'lscheibel/redux-yjs-bindings' && github.ref == 'refs/heads/main'
        with:
          name: build
          path: ./examples/todo-mvc/build/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build-example
    if: github.repository == 'lscheibel/redux-yjs-bindings' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./examples/todo-mvc/build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./examples/todo-mvc/build/
